// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx9LNzwMnGfCEBJk-OsgPIy5kmb76rSLM',
    appId: '1:785957932311:web:6ca3dc2e0f592147c37b52',
    messagingSenderId: '785957932311',
    projectId: 'book-sharing-application',
    authDomain: 'book-sharing-application.firebaseapp.com',
    storageBucket: 'book-sharing-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnZ1qj4ionRbsLJgcTrbjITGvaNWR7CU4',
    appId: '1:785957932311:android:0004fcd856b9c835c37b52',
    messagingSenderId: '785957932311',
    projectId: 'book-sharing-application',
    storageBucket: 'book-sharing-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmFFXFBjtwtOZqPy6OPpBe_3ZXhGKUdcQ',
    appId: '1:785957932311:ios:8c22143922a505f1c37b52',
    messagingSenderId: '785957932311',
    projectId: 'book-sharing-application',
    storageBucket: 'book-sharing-application.appspot.com',
    iosBundleId: 'com.booksharing.booksharingServiceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmFFXFBjtwtOZqPy6OPpBe_3ZXhGKUdcQ',
    appId: '1:785957932311:ios:8c22143922a505f1c37b52',
    messagingSenderId: '785957932311',
    projectId: 'book-sharing-application',
    storageBucket: 'book-sharing-application.appspot.com',
    iosBundleId: 'com.booksharing.booksharingServiceApp',
  );
}
